"""empty message

Revision ID: 15101c0b2ec5
Revises: 4baeef7ede3c
Create Date: 2023-06-17 10:03:21.129218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15101c0b2ec5'
down_revision = '4baeef7ede3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
