"""empty message

Revision ID: 4883aec857e5
Revises: 15101c0b2ec5
Create Date: 2023-06-19 14:44:20.148992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4883aec857e5'
down_revision = '15101c0b2ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(length='finished'), nullable=True))

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Text(length='ongoing'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('finished_task', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
