"""empty message

Revision ID: 4baeef7ede3c
Revises: d82dd5618f88
Create Date: 2023-06-17 09:46:03.585824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4baeef7ede3c'
down_revision = 'd82dd5618f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('filename')
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.TEXT(), nullable=True))
        batch_op.alter_column('picture',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
